<a href="https://colab.research.google.com/github/CibeleYamada/python_xpe_bootcamp/blob/main/Pt2_Aula2_6_Opera%C3%A7%C3%B5es_aritm%C3%A9ticas_no_Numpy_(soma%2C_subtra%C3%A7%C3%A3o_e_divis%C3%A3o).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **OPERAÇÕES ARITMÉTICAS NO  NUMPY ARRAY**

- operações elemento a elemento;
- broadcasting

**Funções aritméticas de soma, subtração e divisão**



In [ ]:
import numpy as np

In [ ]:
# Criação de 2 arrays x e y para exemplificar as operações:

x = np.ones((2,2), dtype=int)
y = np.eye(2, dtype=int)

print('Array x: \n', x)
print('Array y: \n', y)

Array x: 
 [[1 1]
 [1 1]]
Array y: 
 [[1 0]
 [0 1]]


**SOMA**

- pode ser feita por meio do operador '+' ou;
- através da função: np.add()

In [ ]:
# SOMA: usando operador '+'; a operação é feita entre os elementos das mesmas posições, por isso, os arrays devem ter o mesmo shape.

print('Soma de dois arrays, x e y: \n', x + y)

Soma de dois arrays, x e y: 
 [[2 1]
 [1 2]]


In [ ]:
# SOMA: de um número e um array: cada elemento do array é somado ao número.

soma = np.add(x, 2)
print(soma)

[[3 3]
 [3 3]]


**SUBTRAÇÃO**

- pode ser feita pelo operador '-' ou;
- pela função: np.subtract()

In [ ]:
# Subtração usando operadores;
# Array e número

print(x-2)

[[-1 -1]
 [-1 -1]]


In [ ]:
# Subtração usando função np.subtract() entre arrays:

print(np.subtract(x, y))

[[0 1]
 [1 0]]


**DIVISÃO**

- pode ser usado o operador '/' ou;
- a função: np.divide()


In [ ]:
# Divisão:
# OBS: como não dá para dividir um número por 0, vamos criar outros arrays:

A = np.array(((4,2), (8,6)))
B = np.array(((2,2), (2,2)))

print('Array A:\n', A)
print('Array B:\n', B)

Array A:
 [[4 2]
 [8 6]]
Array B:
 [[2 2]
 [2 2]]


In [ ]:
print(A/B)

[[2. 1.]
 [4. 3.]]


In [ ]:
print(A/2)

[[2. 1.]
 [4. 3.]]


Dessa forma, usando arrays, é muito mais fácil fazer operações sem ter que usar a estrutura 'for' e realizar as operações uma a uma.

**OBS**: Quando o broadcasting não funciona:

- quando as dimensões dos arrays não são consistentes

In [ ]:
# Ex: somando um array de 3 elementos com um array de 2 elementos

np.array([1, 2, 3]) + np.array([1, 2])

ValueError: ignored

In [ ]:
# Porém: somando com array de 1 elemento, significa que estamos somando cada elemento do array 1 ao elemento do array 2.

np.array([1, 2, 3]) + np.array([1])

array([2, 3, 4])

**Combinação de operações**

In [ ]:
print('Combinação de operações: \n', (x+y)/(x-2))

Combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]
