<a href="https://colab.research.google.com/github/CibeleYamada/python_xpe_bootcamp/blob/main/Pt2_2_8_Compara%C3%A7%C3%B5es_e_indexa%C3%A7%C3%A3o_booleana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **COMPARAÇÕES E INDEXAÇÃO BOOLEANA**

- comparações entre numpy arrays
- indexação booleana (forma de se realizar uma filtragem no numpy array com  um determinado propósito)



In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])
B = np.array([2,0,2])
s = 3

In [9]:
x = np.array([[1,2], [3,4]])
y = np.array([1.5, 3.5])

**Comparação: menor e menor/igual**

- menor: operador '<'
- menor ou igual: operador '<='

As comparações retornam um outro numpy array que informa se as condições de comparação são verdadeiras ou falsas.

- As comparações são feitas elemento a elemento das posições correspondentes.

In [3]:
# a comparação é feita entre os elementos que ocupam as mesmas posições no array.

print(A < B)

[ True False False]


In [4]:
# podemos fazer a comparação entre um array e um número: o número será comparado com cada elemento do array

print(A < s)

[ True  True False]


In [5]:
print(A <= B)

[ True False False]


In [6]:
print(A <= s)

[ True  True  True]


**Comparação maior e maior/igual**

- maior: operador '>'
- maior ou igual: '>='

**Comparação de igualdade**

- operador: '=='

**Comparação de diferença**

- operador: '!='

In [10]:
print('Comparação de um array com um escalar (>): \n', x > 2)
print('Comparação de um array com um escalar (>=): \n', x >= 2)
print('Comparação de um array com um escalar (<): \n', x < 2)
print('Comparação de um array com um escalar (<=): \n', x <= 2)
print('Comparação entre arrays (==): \n', x == y)
print('Comparação entre arrays (>):\n', x > y) # broadcasting: comparação de linha a linha de x com a linha de y


Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[False False]
 [False False]]
Comparação entre arrays (>):
 [[False False]
 [ True  True]]


#**INDEXAÇÃO BOOLEANA**

- operação de filtro
- retorna um subarray contendo somente a cópia dos elementos em que a condição de verificação se aplica.

In [8]:
# dado o array A dos exemplos acima, queremos verificar a seguinte condição::

cond = A <= 2
D = A[cond]

print('Condição:', cond)
print('Subarray retornado: ', D)

# o subarray retornado (D) só mostra os valores em que a condição é verdadeira.

Condição: [ True  True False]
Subarray retornado:  [1 2]


In [11]:
# Outro exemplo: vamos criar um outro array primeiro

m = np.array([[1,3,7],
              [4,11,21],
              [42,8,9]])

print('m: \n', m)

m: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [14]:
# Agora sim, outro exemplo de indexação booleana: retornar o número de elementos maiores que k

k = 10
cond = m > k

print('Elementos maiores que k: \n', m[cond])

Elementos maiores que k: 
 [11 21 42]


In [13]:
# indexação booleana: extração de números pares

cond = m % 2 == 0

print('Números pares: \n', m[cond])

Números pares: 
 [ 4 42  8]
