#**OPERAÇÕES ÚTEIS NO NUMPY**

In [1]:
import numpy as np

In [2]:
# criando um array:

x = np.array([[1,3,7],
              [4,11,21],
              [42,8,9]])

**Método .reshape**

- transforma a matriz em um vetor coluna ou linha

In [ ]:
# nesse caso, a matriz x (que tem formato 3x3), vira uma matriz coluna 9x1

print(x.reshape(9,1))

[[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [ ]:
# ou uma matrix 1x9 (1 linha, 9 colunas)

print(x.reshape(1,9))

[[ 1  3  7  4 11 21 42  8  9]]


**Método .T - Transposição da matriz**

- faz a transposição da matriz (linha vira coluna e vice-versa)

In [ ]:
print('Matriz transposta de x: \n', x.T)

Matriz transposta de x: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


**Método np.sum()**

- soma os elementos de um determinado eixo ou de toda a matriz.
- lembrando que o eixo 0 é o eixo das linhas e o eixo 1 é o eixo das colunas

In [ ]:
print('Matriz x:\n', x)

print('Soma de todos os elementos da matriz x: \n', np.sum(x))

print('Soma dos elementos ao longo das linhas da matriz x:\n', np.sum(x, axis=0))

print('Soma dos elementos ao longo das das colunas da matriz x:\n', np.sum(x, axis=1))

Matriz x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
Soma de todos os elementos da matriz x: 
 106
Soma dos elementos ao longo das linhas da matriz x:
 [47 22 37]
Soma dos elementos ao longo das das colunas da matriz x:
 [11 36 59]


**Método np.mean()**

- retorna a média ao longo de um eixo.

In [5]:
print('x: \n', x)

print('Média de todos os elementos de x:', np.mean(x))

print('Média de x ao longo das linhas:', np.mean(x, axis=0))

print('Média de x ao longo das colunas:', np.mean(x, axis=1))

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
Média de todos os elementos de x: 11.777777777777779
Média de x ao longo das linhas: [15.66666667  7.33333333 12.33333333]
Média de x ao longo das colunas: [ 3.66666667 12.         19.66666667]


**Outros análogos ao .sum e .mean:**

- np.median(): retorna a mediana;

**Método np.where()**

- muito útil quando trabalhamos com indexaçao booleana;
- identificação dos índices onde uma dada condição é atendida.

In [6]:
# condição: números pares

cond = x % 2 == 0

print('Condição: \n', cond)

# método np.where():

i, j = np.where(cond)

print('índice i (linhas):', i)
print('índice j (colunas):', j)

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
índice i (linhas): [1 2 2]
índice j (colunas): [0 0 1]
