<a href="https://colab.research.google.com/github/CibeleYamada/python_xpe_bootcamp/blob/main/Pt2_Aula2_2_Cria%C3%A7%C3%A3o_de_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [1]:
# importando a biblioteca Numpy e a apelidando de 'np' - que já é comum entre a comunidade

import numpy as np

# **Criação de arrays**

- para usar o numpy array, usamos o método:

**(np.array)** ou (numpy.array)

In [2]:
# dica: a primeira vez que usarmos qualquer método, é sempre usar o 'help' desse método para poder ver casos de uso e como usar o método em específico.
# Para chamar o 'help' do método, usamos o termo 'help' seguido do método:

help(np.array)

# também pode ser chamado de outra forma: 'np.array?'

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [3]:
# Criação de array 1D (unidimensional): [1, 2, 3]

# a) criamos uma lista:
l = [1, 2, 3]

# b) para chamar o array, usamos:
x = np.array(l)

print(x)            # retorna o array
print(x.shape)      # retorna o shape do array

# lembrando que o shape é a quantidade de elementos que tem em cada eixo.

[1 2 3]
(3,)


In [ ]:
# teríamos o mesmo resultado, se colocássemos a lista diretamente na chamada do array:

x = np.array([1, 2, 3])

In [5]:
# Criação de um array 2D (bidimensional) - listas aninhadas
# Criamos uma lista de listas (listas aninhadas); estamos criando uma matriz em que a primeira lista representa a 1ª linha e a 2ª lista representa a 2ª linha da matriz. 

l2 = [[1,2],[3,4]]   # cada bloco é uma linha
y = np.array(l2)
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [7]:
# verificando os tipos das variáveis x, observamos que elas são do tipo numpy array

type(x)


numpy.ndarray

**Algumas funções com os arrays**

- np.zeros(dimensão) - cria array contendo apenas zeros.
- np.ones(dimensão) - cria array contendo apenas números 1.
- np.linspace(inicio = , fim = , numero de elementos =  ) - cria um array com valores linearmente espaçados dentro de um intervalo. É útil para regressões lineares.
- np.eye(n) - cria uma matriz identidade (aquela em que o número de linhas é igual o número de colunas e a diagonal principal tem valores iguais a 1 e as demais posições valem 0). 'n' é o número de linhas (que vai ser igual ao de colunas).
- np.random.random(size=()) - cria um array com valores aleatórios entre 0 e 1.

In [12]:
# Criando arrays que contem apenas 0 (zeros):

# a) Array 1D com shape 5:
z = np.zeros(5)
print('array 1D: ', z)

# b) Array 2D com shape(2,3) - 2 linhas e 3 colunas:
t = np.zeros((2,3))
print('array 2D: \n', t)       # lembrando que \n é quebra de linha

array 1D:  [0. 0. 0. 0. 0.]
array 2D: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Criando arrays que contém apenas 1 (um):

# a) Array 1D com shape 3:
n = np.ones(3)
print('Array 1D: ', n)

# b) Array 2D com shape (3,3):
m = np.ones((3,3))
print('Array 2D: \n', m)

Array 1D:  [1. 1. 1.]
Array 2D: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


OBS: repare que nos arrays criados, os números vieram com pontos (são, portanto, float). Podemos forçar a criação de 0 e 1 como números inteiros, usando **dtype=int**. Ex:

In [14]:
a = np.ones((3), dtype=int)
print(a)

[1 1 1]


In [17]:
# Criação de array com valores linearmente espaçados dentro de um intervalo.
# Sintaxe: np.linspace(start= , stop= , num= )

# Vamos criar um array com 6 elementos, cujos valores devem ficar entre 5 a 15.

b = np.linspace(start= 5, stop= 15, num= 6, dtype=int)     # ainda usamos o dtype=int para forçar a escolha de números inteiros
print(b)
print(b.shape)

[ 5  7  9 11 13 15]
(6,)


In [21]:
# Criação de uma matriz identidade.
# Sintaxe: np.eye(n) em que 'n' é o número de linhas=colunas.

c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# Criação de uma matriz com valores aleatórios:
# Sintaxe: np.random.random(size=())

d = np.random.random(size=(2, 3))      # tamanho(2,3)= 2 linhas, 3 colunas
print(d)

[[0.70379423 0.03365494 0.80606983]
 [0.63860698 0.23707371 0.31013694]]


In [24]:
help(np.random.random)    # ajuda sobre o np.random.random

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.

